### ISSUE TITLE
Issue in capturing screenshot of a webElement on Chrome(Mac)

### ISSUE THREAD

**Issue by RJ05** [yandex-qatools/ashot#102]
Hi,

I am not able to capture complete Web Element, Also there is some issue with the color as well.

At times, It doesn't even capture the correct element.

`Screenshot screenshot= new AShot().coordsProvider(new WebDriverCoordsProvider()).takeScreenshot(driver,webElement) ;`

![image](https://user-images.githubusercontent.com/11192088/27424426-5b283d22-5778-11e7-8c2c-f925a06b3a20.png)

Thanks.

**Comment by kaygee** [comment]
I'm having the same problem.

**Comment by kaygee** [comment]
@RJ05 you might want to read this thread https://github.com/yandex-qatools/ashot/issues/72. Pay attention to this documentation https://github.com/yandex-qatools/ashot/wiki/Shooting-strategies.
