### ISSUE TITLE
Unable to get screenshot in headless Chrome

### ISSUE THREAD

**Issue by olalob** [yandex-qatools/ashot#103]
Hello,

I try to get a screenshot in headless Chrome (inside Docker) via

`
Screenshot screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(10)).takeScreenshot(driver)
`

and on-time get the Execption:

> java.lang.RuntimeException: Unexpected result for screenshot command: null
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:391)
	at ru.yandex.qatools.ashot.shooting.SimpleShootingStrategy.getScreenshot(SimpleShootingStrategy.java:31)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:53)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:35)
	at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:145)

and next time another:

>java.lang.NullPointerException
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getCurrentScrollY(ViewportPastingDecorator.java:80)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:54)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:35)
	at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:145)

but never without error :(

Maybe I must use another Strategy? Without ViewPortPasting I get no errors, but the created screenshot has only the viewable part of page without scrolling.

Could You please help me?
Thanks.

**Comment by olalob** [comment]
if You need my system info:

- Ubuntu 16.04 64-bit
- Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- Chrome Driver 2.30
- Selenium 3.4.0
- Java 8.0_131

**Comment by pazone** [comment]
Hi, @olalob Could you please provide the docker image which is used for it?

**Comment by olalob** [comment]
Hello @pazone, here is my Docker file:
`FROM ubuntu:xenial

# Update & upgrade system
RUN apt-get update && \
	apt-get upgrade -yq

# Install required packages
RUN apt-get install -yq wget ca-certificates openjdk-8-jre-headless

# Install Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
	sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
	apt-get update && \
	apt-get install -yq google-chrome-stable

# Install international fonts
RUN apt-get install -yq fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core

# Installation cleanup
RUN apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create data directory
RUN mkdir /data
WORKDIR /data

# Add chrome user
RUN addgroup chrome && \
	useradd -m -g chrome chrome
USER chrome

# Expose Chrome remote debugging port
EXPOSE 9222`

**Comment by pazone** [comment]
Have you tried to use common image from [here](https://hub.docker.com/r/selenium/node-chrome/ ) or [here](https://hub.docker.com/u/selenoid/)?
I don't see anything like `xvfb` in you Dockerfile. It looks like it has no graphic environment.
What's the purpose of custom docker image?

**Comment by pazone** [comment]
So, the solution is to use common docker image or to add `xvfb`. It will help. Good luck!

**Comment by olalob** [comment]
Thanks! I try Your suggestion.

**Comment by GrzegorzDrozd** [comment]
But purpose of headless chrome (that has been added recently) is to
eliminate need of xvfb.

Can you please fix that.
