### ISSUE TITLE
Screenshot only capturing upper-left corner of the visible window

### ISSUE THREAD

**Issue by 1hella** [yandex-qatools/ashot#104]
I'm having trouble capturing the entire page. It appears to only be capturing the top-left corner of the page.

```
webDriver.navigate().to("https://www.reddit.com/");
				
String screenshotDirectoryPath = "target/site/screenshots/test/";
new File(screenshotDirectoryPath).mkdirs();
		
String outputFileName = "reddit.jpg";
File outputFile = new File(screenshotDirectoryPath + "/" + outputFileName);

Screenshot takeScreenshot = new AShot()
		.shootingStrategy(ShootingStrategies.viewportPasting(100))
		.takeScreenshot(Browser.getDriver());
BufferedImage image = takeScreenshot.getImage();

try {
	ImageIO.write(image, "jpg", outputFile);
} catch (IOException e1) {
	System.out.println("Unable to save screenshot");
	e1.printStackTrace();
}
```
Here's the screenshot I get with this code:
![reddit](https://user-images.githubusercontent.com/6580703/28444520-a194bff0-6d72-11e7-9cc2-a8f57eaa6195.jpg)

And here's a comparable screenshot I got using a chrome plugin:
![download](https://user-images.githubusercontent.com/6580703/28444541-ca0b328e-6d72-11e7-9216-828c5f8e265b.png)

Specs:
* Google Chrome 59.0.3071.115 (Official Build) (64-bit)
* Chromedriver 2.29
* Mac OS Sierra 10.12.5 
* 2880 x 1800 resolution
* Selenium 3.4.0
* Java 8

**Comment by pazone** [comment]
@1hella Thanks for report! I guess it is related to https://github.com/yandex-qatools/ashot/issues/96

**Comment by 1hella** [comment]
No problem. Is there anything I can do to help?

**Comment by pazone** [comment]
We are investigating this problem

**Comment by pazone** [comment]
@1hella Sorry for confusing you. The problem is that your screen DPR is _2_ (Retina display). Taken image is 4 times bigger than it actually is. We have workaround for it. Take a look to `ShootingStrategies` factory. You can find `viewportRetina` method there. That's exactly you are looking for.

**Comment by 1hella** [comment]
@pazone Got it, thanks.

Changing from `.shootingStrategy(ShootingStrategies.viewportPasting(100))` to `.shootingStrategy(ShootingStrategies.viewportRetina(100, 0, 0, 2))` works for me.

**Comment by TariqueKhanANX** [comment]
image size got reduced and only capturing the current viewport in MacOS High Sierra (Chrome and Firefox)
   ` final Screenshot screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportRetina(100, 0, 0, 2)).takeScreenshot(driver);`
