### ISSUE TITLE
Different screenshot size for Chrome and Firefox on same machine and same test case on retina screen

### ISSUE THREAD

**Issue by tlytvyn** [yandex-qatools/ashot#17]
I am using MacBook Pro with Retina screen. Chrome Driver 14 and Firefox 36.
On Windows with Full HD screen I am getting same resolution screenshots. 
On Mac with Retina I've got for Chrome 2560x1274 screenshot and for FF 1280x630.

How can I get smaller screens for Chrome ?

**Comment by pazone** [comment]
In this case you should have separate AShot configs to both browsers. For chrome use ```dpr(2)``` to tell AShot that device pixel ratio is 2(retina) and AShot will resize the shot. 
I am using AShot with iPad, and Andriod devices and I have the factory of AShot's configs matching the browsers and platforms.

**Comment by tlytvyn** [comment]
works for me, thanks a lot.
