### ISSUE TITLE
Element blur screenshots are cropped incorrectly on retina screen in Google Chrome

### ISSUE THREAD

**Issue by tlytvyn** [yandex-qatools/ashot#18]
I am using this method to crop element screenshot:
private static BufferedImage blurElementOnScreenShot(WebDriver driver,
			WebElement element) {
		Screenshot imageScreen = new AShot()
				.coordsProvider(new WebDriverCoordsProvider())
				.imageCropper(new IndentCropper() // overwriting cropper
						.addIndentFilter(new BlurFilter()))
				.takeScreenshot(driver, element); // adding filter for indent

		return imageScreen.getImage();
	}

and I am using MAcBook Pro with retina - images are cropped incorrectly in Chrome. The blur effect highlight images incorrectly. 
!!! But everything is fine for Firefox browser.

**Comment by pazone** [comment]
For chrome use ```dpr(2)``` to tell AShot that device pixel ratio is 2(retina). The size of elements 2 times bigger than their coords&

**Comment by tlytvyn** [comment]
yeap, that's works for me
