### ISSUE TITLE
VerticalPastingShootingStrategy locally may work wrong

### ISSUE THREAD

**Issue by eoff** [yandex-qatools/ashot#20]
If you need to make screenshots on your local monitor (for example, laptop display) there might occur difference between 
```
$(window).height()
```
and 
```
BufferedImage baseImage = simple().getScreenshot(wd);
int h = baseImage.getHeight();
```
This is because high-resolution monitors (like retina displays) perform image scaling.
For example, I get following values:
```
$(window).height(); 728

BufferedImage baseImage = simple().getScreenshot(wd);
int h = baseImage.getHeight(); 1456
```
and finally this causes missing part of image when parts are combined:
```
for (int n = 0; n < scrollTimes; n++) {
    js.executeScript("scrollTo(0, arguments[0])", winH * n);
    waitForScrolling();
    BufferedImage part = super.getScreenshot(wd);
    graphics.drawImage(part, 0, n * winH, null);
}
```

**Comment by pazone** [comment]
(Dublicate)Use dpr() method. You've got too good computer with retina display. And drp of your display is 2. All in all it should work 
```
 new AShot().dpr(2)........takeScreenshot()
```
