### ISSUE TITLE
Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only

### ISSUE THREAD

**Issue by nikeshjauhari** [yandex-qatools/ashot#38]
I am using 1.4.12
I am getting following warning on using the ashot lib

Jun 01, 2015 1:45:24 PM org.openqa.selenium.remote.Augmenter extractRemoteWebDriver
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only

===================
Code that I am using

WebDriver webDriver = new FirefoxDriver();
webDriver.get("http://www.google.com");
WebElement element = webDriver.findElement(By.name("q"));
element.sendKeys("Cheese!");
		
Screenshot screenshot =	new AShot()
  .shootingStrategy(new ViewportPastingStrategy(0))
  .takeScreenshot(webDriver);
		
File outputfile = new File("saved.png");
ImageIO.write(screenshot.getImage(), "png", outputfile);
element.submit();

Any reason why I am getting this warning ?

**Comment by pazone** [comment]
Hello. Wich version of selenium are you using?
P. S. Why are you trying to use ViewportPastingStrategy with firefox?

**Comment by pythonmeister-zz** [comment]
I get the same error.
Selenium version 3.141.59.
