### ISSUE TITLE
I can't to take the screenshot

### ISSUE THREAD

**Issue by maxslon** [yandex-qatools/ashot#45]
I use method takeScreenshot(driver, webElement); but it doesn't work in page http://193.0.171.22/23/29/48/1508849232/1508868043_square_incognito.jpg?hash=VFTT1R5jMmaVBTrO253rmQ&expires=1442437199&updated=1442335699

Is it because the page doesn't have JS?
How I can to take screenshon on this page?

**Comment by rovner** [comment]
Hello, @maxslon!
From the documeentation

> As noted earlier aShot will find element's size and position and crop original image. WebDriver API provides a method to find the WebElement's coordinates but different WebDriver implementations behave differently. In my opinion the most general approach to find coordinates is to use jQuery. So aShot uses jQuery by default. But some drivers have problems with Javascript execution such as OperaDriver. In this case there is another way to find the WebElement's coordinates.

```
new AShot()
  .coordsProvider(new WebDriverCoordsProvider()) //find coordinates with WebDriver API
  .takeScreenshot(webDriver, myWebElement);
```

So, it is because of no jQuery on your page. In your case you could just use ```takeScreenshot(driver)``` to take the whole page screenshot I believe.
