### ISSUE TITLE
Taking screenshot on iPad horizontal

### ISSUE THREAD

**Issue by frankvu** [yandex-qatools/ashot#54]
When taking screenshot on iPad horizontally, the screenshot is kept as portrait http://screencast.com/t/vfrXpGlhrs. How should we deal with this?
Thanks

**Comment by pazone** [comment]
Are you using Appium?

**Comment by frankvu** [comment]
Yes, I am using Appium

**Comment by pazone** [comment]
Thanks, this is known problem. In this case we are using special landscaped shooting strategy. I'll try to publish it soon.

**Comment by frankvu** [comment]
Thanks, pazone

**Comment by rovner** [comment]
Hello, frankvu. I've recently added RotatingDecorator. With 1.5.2-SNAPSHOT you could use it like this
```
ShootingStrategy strategy = ShootingStrategies.iPadLandscapeOrientationSimple(scrollTimeout, new FixedCutStrategy(header, footer))
```

In case of retina it will be a little bit more complicated. You should build chain of decorators by yourself, there are no shortcut method for that in ShootingStrategy class.
```
ScalingDecorator scalingDecorator = new ScalingDecorator(ShootingStrategies.simple()).withDpr(dpr);
RotatingDecorator rotatingDecorator = new RotatingDecorator(new FixedCutStrategy(header, footer),  scalingDecorator)
ViewportPastingDecorator(rotatingDecorator).withScrollTimeout(scrollTimeout);
```
