### ISSUE TITLE
Exclude "marked" points from comparison

### ISSUE THREAD

**Issue by dimand58** [yandex-qatools/ashot#56]
Hi, thanks for AShot and please look at this feature request:
- I want mark some area(pixels) in png file (by red/green/any color)
- During autotests AShot should compare actual screenshot and my "marked" screenshot 
- AShot should exclude marked points (with predefined color) from comparison

**Comment by pazone** [comment]
Hello. 
AShot is already can exclude areas or elements when comparing screenshots. Look at ```addIgnoredElement``` and ```addIgnoredArea```

**Comment by dimand58** [comment]
Hi, thanks for reply.
But if I need to exclude many of areas(10-15 input fields and etc)? Code will be monstrous.

In this case exclusion via marked pixels in template will be very usefull.

P.S. I will try create pull request

**Comment by pazone** [comment]
I thing you can do it by this way: ```ashot.addIgnoredElement(By.cssSelector("selector_for_your_intuts"));```. Coords of all your inputs will be added as ignored

**Comment by dimand58** [comment]
Yep, this is another way, but using of screenshot-"mask" will be useful too. I've started work on pull request.

**Comment by pazone** [comment]
@dimand58 How is your pull request? If you need some suggestions, just ask here

**Comment by dimand58** [comment]
@pazone will be done on this week)

**Comment by pazone** [comment]
@dimand58 Ok. Actually, I can fully understand what are you going to do. Notice that bringing a third screenshot to comparison process and produce some memory issues

**Comment by dimand58** [comment]
@pazone pull request was provided, please review

**Comment by pazone** [comment]
@dimand58 thanks

**Comment by OlehPitsyc** [comment]
Hello! 
I have tried to use addIgnoredElement method, and it returned error (screenshot: http://prntscr.com/e9a37q)
I have read some articles about it in your github issues, but there were nothing, about this error in my case with addIgnoredElement. In all other cases it works perfect. 
Please help!
