### ISSUE TITLE
exceuse me,where is the class ViewportPastingStrategy?

### ISSUE THREAD

**Issue by JackieHowe** [yandex-qatools/ashot#60]
I'm afraid i can not find the class  ViewportPastingStrategy,where is it?

**Comment by alcounit** [comment]
Probably it moved out. You can use methods from ShootingStrategies class. For example
 new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000)).takeScreenshot(driver);

**Comment by pazone** [comment]
Ok, it's time to update docs
