### ISSUE TITLE
Not capturing complete view in iOS and Android 

### ISSUE THREAD

**Issue by shivakrishnach31** [yandex-qatools/ashot#61]
I wrote the below code take the screenshots in iOS and Android devices. While capturing screenshot, it is capturing complete screen view by scrolling the page until the timeout session I have given ViewPortPastingStrategy. But after merging all the screenshots, the final screenshot showing a portion of screenshot only not complete screenview.
Attached individual screenshots and finals screenshot. Code is below

final Screenshot screenshot = new AShot().shootingStrategy(new ViewportPastingStrategy(1000)).takeScreenshot(driver);
			final BufferedImage image = screenshot.getImage();
			ImageIO.write(image, "PNG", "screenshot_1.png"));
![ipad_ipad mini 2 homepage](https://cloud.githubusercontent.com/assets/8439309/12215346/c95c515c-b6de-11e5-9c53-ef86bae58142.png)
![screenshot-selenium-1](https://cloud.githubusercontent.com/assets/8439309/12215347/c95d3c02-b6de-11e5-8ce6-28ea93f7e33c.png)
![screenshot-selenium-2](https://cloud.githubusercontent.com/assets/8439309/12215349/c970bdcc-b6de-11e5-8a03-61cad2496870.png)
![screenshot-selenium-3](https://cloud.githubusercontent.com/assets/8439309/12215348/c96fded4-b6de-11e5-8ae8-bd57936c2ad9.png)
![screenshot-selenium-4](https://cloud.githubusercontent.com/assets/8439309/12215350/c97593f6-b6de-11e5-8be8-8de1f92c9524.png)

**Comment by rovner** [comment]
Hi, shivakrishnach31. It looks like you have a retina device, so you need to scale your screenshots with ```ScalingDecorator```. Also you need to cut browser header with ```CuttingDecorator```. For convenience there are several shortcut methods in ```ShootingStrategies```. Probably, you could use ```iPad2WithIOS8RetinaSimulator``` or ```iPad2WithIOS8Retina```. If not, please, try ```viewportRetina``` method.

**Comment by shivakrishnach31** [comment]
Thankyou @rovner , It is working now. But for Android also I have used 'iPad2WithIOSRetinaSimulator' . I believe that was not good practice. Do we have any other method to do this for Android emulators?

**Comment by pazone** [comment]
@shivakrishnach31 Wich Android emulator do you prefer? Also try to avoid retina displays. It can produce some memory issues with large pages.

**Comment by shivakrishnach31** [comment]
@rovner , I want screenshots in Phone and Tablet. Do we have any other method to capture proper screenshots in Android phone and tablet other than `iPad2WithIPSRetinaSimulator`. Actually when I used  `iPad2WithIPSRetinaSimulator` to capture screenshots in Android phone and tablet, the webpage header slightly cut off in screenshots. Is this because of `iPad2WithIPSRetinaSimulator` ?. Could you please help me to get the proper screenshot in Android phone and tablet.

**Comment by rovner** [comment]
@shivakrishnach31,  there are no shortcut methods for android phone and tablet, because andriod browsers differs a lot. So you have to use ```ShootingStrategies.viewportRetina``` method and provide  proper ```scrollTimeout``` (probably 1000),  ```headerToCut``` (depends on device/emulator), ```footerToCut``` (also depends on device/emulator, most likely it is 0) and ```dpr``` (should be 2F for you) .

**Comment by shivakrishnach31** [comment]
Thanks @rovner . It worked. But there is lot empty space in screenshot. Can't be overcome that empty space. Please see the attached screenshot...


![android_htc one m8 homepage](https://cloud.githubusercontent.com/assets/8439309/12522735/5e359cae-c178-11e5-86e7-482a7e4c0cfe.png)


![android_samsung galaxy tab 4 10 1 homepage](https://cloud.githubusercontent.com/assets/8439309/12522734/5e327f60-c178-11e5-8185-dd3d8049aeaf.png)

**Comment by rovner** [comment]
Hi, @shivakrishnach31! Could you attach code sample for this?

**Comment by pazone** [comment]
So, what's new in this issue? Was problem solved?

**Comment by shivakrishnach31** [comment]
@pazone , Thanks for the support. Yes, the problem got solved.

**Comment by pazone** [comment]
@shivakrishnach31 you are welcome

**Comment by fagnerpaes** [comment]
> Thanks @rovner . It worked. But there is lot empty space(Black coloured area) in screenshot. Can't be overcome that empty space(black coloured area). Please see the attached screenshots...
> 
> ![android_htc one m8 homepage](https://cloud.githubusercontent.com/assets/8439309/12522735/5e359cae-c178-11e5-86e7-482a7e4c0cfe.png)
> 
> ![android_samsung galaxy tab 4 10 1 homepage](https://cloud.githubusercontent.com/assets/8439309/12522734/5e327f60-c178-11e5-8185-dd3d8049aeaf.png)

Hi @shivakrishnach31, @pazone 

There is an opne issue #124 that reported the same problem.

How were you resolve the problem?

Thanks!

**Comment by Kiera11** [comment]
Hi,
@shivakrishnach31 
I would like to know how did u test for different devices such as:
Iphone
Samsung 
Ipad

I have indeed use the following: 
new AShot().shootingStrategy(ShootingStrategies.viewportRetina(1000,0,0,2F))
but the screenshot taken are for ipad.

Thanks,
