### ISSUE TITLE
ViewportPastingStrategy not available

### ISSUE THREAD

**Issue by andrew-sumner** [yandex-qatools/ashot#63]
The readme states that I should using the following code but ViewportPastingStrategy() doesn't exist in 1.5.2.

new AShot()
  .shootingStrategy(new ViewportPastingStrategy())
  .takeScreenshot(webDriver);

**Comment by pazone** [comment]
We forgot to update docs. Sorry :)

**Comment by pazone** [comment]
got a bug about it
