### ISSUE TITLE
Getting WebDriverException when using AShot in my project to capture a webelement 

### ISSUE THREAD

**Issue by azhwani** [yandex-qatools/ashot#68]
Hii Ashot Team,
I'm getting WebDriver Exception for taking screenshot of an invisible element (need to scroll down to find this element).
**Exception:**
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: $ is not defined
**Code :**
WebElement element = driver.findElement(By.cssSelector("#imgId"));
Screenshot screenshot = new AShot().shootingStrategy(new ViewportPastingStrategy(1000)).takeScreenshot(driver,element);
ImageIO.write(screenshot.getImage(), "PNG", new File("C:\\screenshot.png"));

**Comment by frolovs** [comment]
Hi @azhwani ,
exception shows that probably you have no jQuery on your web page.
jQuery is still required by AShot ( coords-single.js ). 
Also I can see that you use quite an old version of AShot.
Hope it helps.

**Comment by thasherwin** [comment]
Hi Ashot folks,

Would including jquery on the page using Selenium solve this issue? I have seen a post on http://sqa.stackexchange.com/questions/2921/webdriver-can-i-inject-a-jquery-script-for-a-page-that-isnt-using-jquery to include Jquery. I faced the same issue sometimes and it would be great if ashot works all the time.

thanks,

**Comment by pazone** [comment]
use ```aShot. coordsProvider(new WebDriverCoordsProvider())``` if you don't have jQuery on your page. ```WebDriverCoordsProvider``` not uses jQuery for position calculating.

**Comment by thasherwin** [comment]
great thanks. i will try this
