### ISSUE TITLE
Page elements are not ignored

### ISSUE THREAD

**Issue by pavelpp** [yandex-qatools/ashot#69]
I'm using this construction to exclude elements on my page from diff comparison:

```
AShot shooter = new AShot().shootingStrategy(ShootingStrategies.simple())
                .ignoredElements(ignoredElements).coordsProvider(new WebDriverCoordsProvider());
```

However my test is failing and I see marked image with areas it's supposed to ignore.

Ashot version 1.5.2

**Comment by pavelpp** [comment]
I figured I need to set setIgnoredAreas for reference image as well, which is not very convenient, as I need first to get coords of all ignored elements, load reference image as BufferedImage, then convert to Screenshot, then setIgnoredAreas and finally make diff.

**Comment by pavelpp** [comment]
Multiple coords in a Set<Coords> aren't applied for some reason. Only the first element in a set is ignored. I see there's no test for this scenario.

**Comment by pazone** [comment]
Hello.
Now you are trying to do exactly what AShot does. I need more context to give exact answer. Which browser are you using? What kind of element you are trying to ignore?

**Comment by pavelpp** [comment]
Hi. I'm using Chrome in a docker container http://testcontainers.viewdocs.io/testcontainers-java/usage/webdriver_containers/ with selenium version 2.53.0 with window size set to 1280x720.

The elements are just common web elements, like "header" , "input" etc. I've now added a helper method which sets ignored areas the way I listed in previous post and it kinda works.

I also have a question - how do you handle fonts being rendered differently on different systems and on different browsers? Do you keep reference images for each combination of system+browser?

**Comment by pazone** [comment]
Different fonts appears if the main font is absent. Look at your page's css what is the top priority font and try to install it in your `Dockerfile`'s. Then rebuild your images. If you are comparing images, use `setDiffSizeTrigger` in `DiffMarkupPolicy` to ignore little diffs. 
Can you show the page and the element you trying to ignore?

**Comment by pavelpp** [comment]
Makes sense. The page is not public, so I can't provide any links. I'll try some random public page and see if I can reproduce the problem.

**Comment by pavelpp** [comment]
Here's a test you can reproduce yourself. I'm using Selenide

```
 package zt.selenide.junit;

import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import ru.yandex.qatools.ashot.AShot;
import ru.yandex.qatools.ashot.Screenshot;
import ru.yandex.qatools.ashot.comparison.ImageDiff;
import ru.yandex.qatools.ashot.comparison.ImageDiffer;
import ru.yandex.qatools.ashot.shooting.ShootingStrategies;
import zt.selenide.junit.rules.BaseTest;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;

import static com.codeborne.selenide.Selenide.*;
import static org.junit.Assert.assertFalse;

public class YandexTest extends BaseTest {

    @Test
    public void ignoredElementTest() throws Exception {
        String reference = "yandex.png"; // assume there is a reference file
        String randomText = "qseferqinsdvjniu132rc349jh9132rcdsaf";

        open("http://ya.ru");
        $(".input__input").click();
        $(".input__input").sendKeys(randomText);

        AShot ashot = new AShot()
                .addIgnoredElement(By.cssSelector(".input__input"))
                .shootingStrategy(ShootingStrategies.simple());

        Screenshot actual = ashot.takeScreenshot(WebDriverRunner.getWebDriver());

        BufferedImage ref = ImageIO.read(ClassLoader.getSystemResourceAsStream("reference/images/chrome/" + reference));

        ImageDiff diff = new ImageDiffer().makeDiff(new Screenshot(ref), actual);
        if (diff.hasDiff()) {
            File diffFile = new File(Configuration.reportsFolder + "/diff-" + reference);
            File actualFile = new File(Configuration.reportsFolder + "/actual-" + reference);
            diffFile.mkdirs();
            actualFile.mkdirs();
            ImageIO.write(actual.getImage(), "png", actualFile);
            ImageIO.write(diff.getMarkedImage(), "png", diffFile);

            assertFalse("Images are not equal!", diff.hasDiff());
        }
    }
}
```

**Comment by pazone** [comment]
Oh, I understood. This is not obvious thing. `ImageDiffer` ignores intersections between ignored elements on both screenshots. Your referenced screenshot has no ignored coords and no intersections with actual ignored coords. So you should save not only reference image and also write ignored areas. This is not hard, just write a helper to save screenshot and additional info. 
Thank you for a good use-case. If you'll got any questions, just welcome.

**Comment by pavelpp** [comment]
That's basically what I was trying to say. I created a helper method, but loading these coords for ref image could be "automagic" as we pass element locators anyway and can derive coordinates from those. Then there would be no need for helper methods.

**Comment by pazone** [comment]
How do you update reference image? Can you show your helper method? Anyway you should just save `coodsToCompare` and `ignoredCoords` besides reference image.

**Comment by pavelpp** [comment]
```
    private static Set<Coords> getCoords(Set<By> ignoredElements) {
        Set<Coords> ignoredCoords = new HashSet<>();
        for (By locator : ignoredElements) {
            Point point = $(locator).getLocation();
            Dimension dimension = $(locator).getSize();
            ignoredCoords.add(new Coords(point.getX(), point.getY(), dimension.getWidth(), dimension.getHeight()));
        }
        return ignoredCoords;
    }
```

**Comment by pavelpp** [comment]
actually storing reference coordinates in a separate file kind of makes sense.. Need to think about it a bit

**Comment by pavelpp** [comment]
yeah, my method would only work for whole page screenshots, not for page blocks

**Comment by pazone** [comment]
Of course. Try to implement `Screenshot` file serializer

**Comment by pavelpp** [comment]
Totally makes sense. Thanks!

**Comment by loveshjain** [comment]
Hi pavelpp,

Could you please share how you find the solution for the above issue. I am getting the same problem wherein if I compare a ref image which already exist when I first run the test with an actual image having ignored element to it does not actually ignore the area. 
However if I compare 2 screenshot with ignored areas in the same run then it works like a charm.

Many thanks in advance.

Thanks,
Lovesh

**Comment by pavelpp** [comment]
@loveshjain , I serialised reference screenshots, containing ignored areas info. Then during test I de-serialised and compared.

**Comment by ksiv** [comment]
"Oh, I understood. This is not obvious thing. ImageDiffer ignores intersections between ignored elements on both screenshots. "
would be nice if you share your understanding.
here 
https://github.com/yandex-qatools/ashot/#screenshot-comparison

 from this page it's not clear that : **".addIgnoredElement"** <- it's not enough.
Keep the code as is though since runtime
otherScreenshot.setIgnoredAreas(currentScreenshot.getIgnoredAreas());
works just fine.

**Comment by Merckan** [comment]
Can someone tell me, what is wrong with my code?
Why ignored area is still comparing?

    public void runTest() throws IOException {
        String url ="https://yandex.ru/";
        String xpath = "//input[@id='text']";
        open(url);
        $x(xpath).waitUntil(visible, 5000).sendKeys("123yuiouioyioyioioio12312i3yio12y3io12io3");
        Set<By> bySet = new HashSet<>();
        bySet.add(By.xpath(xpath));

        Screenshot screenshot1 = new AShot()
                .shootingStrategy(ShootingStrategies.viewportPasting(500))
                .ignoredElements(bySet)
                .takeScreenshot(getWebDriver());

        Set<Coords> ignoredCoords = screenshot1.getIgnoredAreas();
        BufferedImage bufImage1 = screenshot1.getImage();

        refresh();
        $x(xpath).waitUntil(visible, 5000).sendKeys("789a7df8a98z7zc987c9v7c89zx7897cx89vz7c8x9v");
        Screenshot screenshot2 = new AShot()
                .shootingStrategy(ShootingStrategies.viewportPasting(500))
                .takeScreenshot(getWebDriver());

        screenshot2.setIgnoredAreas(ignoredCoords);
        BufferedImage bufImage2 = screenshot2.getImage();

        ImageDiff diff = new ImageDiffer().makeDiff(bufImage1, bufImage2);
        BufferedImage diffImage = diff.getMarkedImage();

        createImageFromBuffer(diffImage, "src/main/results/diff.png");
        assertEquals(bufImage2, diffImage);
    }

    protected String createImageFromBuffer (BufferedImage bufImage, String filePath) {
        File image = new File(filePath);
        try {
            ImageIO.write(bufImage, "png", image);
        } catch (IOException e) {
            e.printStackTrace();
            fail();
        }
        return "Image has been saved: \n"+image.getAbsolutePath();
    }

Result of comparing:
![yandex_test](https://user-images.githubusercontent.com/43963611/46620080-677c5080-cb2c-11e8-9079-8d985a0725f1.jpg)

**Comment by stnnznk** [comment]
@Merckan  the same problem with ignoring
@pazone can u help us
