### ISSUE TITLE
Issue with taking full screenshot for IE  browser

### ISSUE THREAD

**Issue by ramuboj** [yandex-qatools/ashot#70]
getting below error:

java.lang.NullPointerException
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getCurrentScrollY(ViewportPastingDecorator.java:79)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:54)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:35)
	at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:143)

**Comment by pazone** [comment]
Hello. Could you please provide code snippet where you are configured AShot.
Obvoiusly you should not use `ViewportPastingDecorator` for IE. Default shooting strategy is suitable for IE

**Comment by ramuboj** [comment]
thanks for the mail, its worked with default shooter.! i thought to use
same api for all the browsers.!
it will be good if its compatible for IE as well.

Thanks, Ram

**Comment by hemano** [comment]
screenshot = new AShot().takeScreenshot(driver);

is still giving me NPE for IE 11.

**Comment by umohan** [comment]
@pazone 
In Internet Explorer 11,
while using `new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000)).takeScreenshot(wb)`
an image having same size as webpage is created but their is screenshot of only last port view
![scr2](https://user-images.githubusercontent.com/20687530/34987809-7d591a16-fae2-11e7-8a36-e3d78b60ee0e.png)

even  `new AShot().takeScreenshot(wb)` is not working properly
can u help me with this?
