### ISSUE TITLE
Getting black spot on the Chrome - Tablet Emulator screenshot while Capturing the entire page

### ISSUE THREAD

**Issue by seliniumtester** [yandex-qatools/ashot#71]
Getting black spot on the Chrome-Tablet emulator screenshot while Capturing the entire page by using 
new AShot()
  .shootingStrategy(ShootingStrategies.viewportPasting(100))
  .takeScreenshot(webDriver);

Same works fine for Chrome- Phone emulator.

Please provide resolution for this issue.

Here is the code.
    String baseUrl = "https://github.com/yandex-qatools/ashot";

```
    Map<String, String> mobileEmulation = new HashMap<String, String>();
    mobileEmulation.put("deviceName", "Apple iPad");
    Map<String, Object> chromeOptions = new HashMap<String, Object>();
    chromeOptions.put("mobileEmulation", mobileEmulation);
    DesiredCapabilities capabilities = DesiredCapabilities.chrome();
    capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
    WebDriver driver = new ChromeDriver(capabilities);
    driver.manage().window().maximize();

    driver.get(baseUrl);

    final Screenshot screenshot = new AShot()
              .shootingStrategy(ShootingStrategies.viewportPasting(100))
              .takeScreenshot(driver);

    final BufferedImage image = screenshot.getImage();
    ImageIO.write(image, "PNG", new File("C:\\Selenium\\"+ "Ahot-Tablet.png"));
```

Tablet Screenshot:
![ahot-tablet](https://cloud.githubusercontent.com/assets/19582905/15563080/d15d1408-2322-11e6-8d14-4b4e8aa8ae78.png)

Phone Screenshot:
![ahot-phone](https://cloud.githubusercontent.com/assets/19582905/15563098/180d5822-2323-11e6-8f8b-a6d972a3f134.png)

**Comment by pazone** [comment]
Hello. It looks like your phone emulator has `dpr = 1`, but tablet has `dpr > 1`. You should set it in shooting strategy. 

Try to use 
```
new AShot().shootindStrategy(ShootingStrategies.viewportRetina(100, 0, 0, <yourDpr>));

```

**Comment by seliniumtester** [comment]
Hi, Thanks for the suggestion. I have tried the same with the below code,
			final Screenshot screenshot = new AShot()
					  .shootingStrategy(ShootingStrategies.viewportRetina(100, 0, 0, 2))
					  .takeScreenshot(driver);

Now, i am getting more black area. Please advice.

Screenshot:
![1-login1](https://cloud.githubusercontent.com/assets/19582905/15576085/bffdab4a-2373-11e6-800b-a9537d90b706.jpg)

**Comment by pazone** [comment]
As I understood, you are using build in Chrome tools to emulate tablet. Are you using Chrome's presets for it or custom capabilities? Which kind of tablet you want to emulate?

**Comment by seliniumtester** [comment]
Hi, yes i am using the build in Chrome emulator. I am using the below custom capability provided in the chromedriver.exe. I am trying to emulate Apple iPad device.

    Map<String, String> mobileEmulation = new HashMap<String, String>();
    mobileEmulation.put("deviceName", "Apple iPad");
    Map<String, Object> chromeOptions = new HashMap<String, Object>();
    chromeOptions.put("mobileEmulation", mobileEmulation);
    DesiredCapabilities capabilities = DesiredCapabilities.chrome();
    capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
    WebDriver driver = new ChromeDriver(capabilities);

**Comment by pazone** [comment]
Consider this code string `deviceMetrics.put("pixelRatio", 3.0);`   [here](https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation) . You are using preset with unknown pixel ratio. 
Add this to your caps: `deviceMetrics.put("pixelRatio", 1.0);` - it will make your emulation screenshotable :) Also avoid to launch on displays with `DPR != 1`. For example mac book with retina.

**Comment by seliniumtester** [comment]
Hi, I have added the capability as per your suggestion. Still, i am getting this issue. Please advice.

Please find the code below.

Browser Setup:

String baseUrl = "https://github.com/yandex-qatools/ashot";
        Map<String, Object> deviceMetrics = new HashMap<String, Object>();
        deviceMetrics.put("width", 768);
        deviceMetrics.put("height", 1024);
        deviceMetrics.put("pixelRatio", 1.0);
        Map<String, Object> mobileEmulation = new HashMap<String, Object>();
        mobileEmulation.put("deviceMetrics", deviceMetrics);
        mobileEmulation
        .put("userAgent",
        "Mozilla/5.0 (iPad; CPU OS 9_0 like Mac OS X) AppleWebKit/601.1.17 (KHTML, like Gecko) Version/8.0 Mobile/13A175 Safari/600.1.4");
        Map<String, Object> chromeOptions = new HashMap<String, Object>();
        chromeOptions.put("mobileEmulation", mobileEmulation);
        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
        WebDriver driver = new ChromeDriver(capabilities);
        driver.manage().window().maximize();
        
        driver.get(baseUrl);

Screenshot: 

        final Screenshot screenshot = new AShot()
              .shootingStrategy(ShootingStrategies.viewportPasting(100))
    		.takeScreenshot(driver);
        
or
        final Screenshot screenshot = new AShot()
        		  .shootingStrategy(ShootingStrategies.viewportRetina(1000, 0, 0, 1))
        		  .takeScreenshot(driver);

Screenshot:
![ahot-tablet1](https://cloud.githubusercontent.com/assets/19582905/15616937/37f24750-2464-11e6-80a3-4b0e03836c0e.png)

**Comment by pazone** [comment]
Are you getting this when trying to take screenshot of other page? If you are launching chrome locally I need to know you local dpr, it also can be != 1.

**Comment by rovner** [comment]
It's really looks like a bug for me in [viewport_height.js](https://github.com/yandex-qatools/ashot/blob/master/src/main/resources/js/viewport_height.js) for chrome emulation in portrait mode.
See
```
//portrait
window.innerHeight
1360 // should be 1024
document.documentElement.clientHeight
1024
//landscape
document.documentElement.clientHeight
768
window.innerHeight
768
```

@seliniumtester you could workaround your code by using landscape orientation for now
```
        Map<String, Object> deviceMetrics = new HashMap<>();
        deviceMetrics.put("width", 1024);
        deviceMetrics.put("height", 768);
        deviceMetrics.put("pixelRatio", 1.0);

```

**Comment by seliniumtester** [comment]
@pazone yes i am getting this issue in other pages as well. I am having dpr as 1.

@rovner thanks for the suggestion. But, for landscape view also i am getting the same issue,Please refer the below screenshot.

![ahot-landscape](https://cloud.githubusercontent.com/assets/19582905/15654813/d8501afe-26b4-11e6-8940-252e01302874.png)

**Comment by seliniumtester** [comment]
Also i am getting the below warning message in the console when Ashot takes screenshot. Please advice.

May 30, 2016 10:49:06 PM org.openqa.selenium.remote.Augmenter extractRemoteWebDriver
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only

**Comment by pazone** [comment]
@seliniumtester Could you please take look at `ShootingStrategies` factory. You can solve your problem by using `ShootingStrategies.viewportRetina(...)` shooting strategy. You should figure our the DPR of your device to adjust it. Sorry for long response.

**Comment by MayankOkeyUser** [comment]
WebDriver driver = new ChromeDriver();
Object output = ((JavascriptExecutor) driver).executeScript("return window.devicePixelRatio");
String value = String.valueOf(output);
float windowDPR = Float.parseFloat(value);

use DPR  here : 
Screenshot screenshotfull= new AShot().shootingStrategy(ShootingStrategies.viewportRetina(1000, 0, 0, windowDPR)).takeScreenshot(driver);

you will get rid of Black Space from ScreenShot
