### ISSUE TITLE
Unable to see full web page view of mobile web site  

### ISSUE THREAD

**Issue by sanojqa** [yandex-qatools/ashot#72]
I am trying to capture full mobile web page view using Ashot latest jar. Following are the code I used

Screenshot sh = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(500)).takeScreenshot(driver);

BufferedImage fullScreen = sh.getImage();

ImageIO.write(fullScreen, "png", new File("D:\test\"+"coool.png"));

Site: http://www.rapidvaluesolutions.com/

Loaded in Mobile Web and captured using above code.

Attached screenshot.
![coool](https://cloud.githubusercontent.com/assets/9329778/15566951/4e59ec2e-2341-11e6-91bd-a07f906efbba.png)

**Comment by pazone** [comment]
Hello. It looks like your phone emulator has `dpr > 1`. You should set it in shooting strategy. 

Try to use 
```
new AShot().shootindStrategy(ShootingStrategies.viewportRetina(100, 0, 0, <yourDpr>));

```

**Comment by sanojqa** [comment]
@pazone  Thanks for the reply and I got some difference in Screenshot but I am getting 60-70% image of the web page and the images are overlapped when I tried this snippet with different websites. For the above website I have set the dpr is 1.8 and I got good result, when I use the same configuration for other sites am getting overlapping images and cutting right side of the page. When I use the dpr 3 then a black shade came across the images in each frame capturing.

Have any alternative to solve this inconsistent behavior in different sites with same configuration?

Thanks,
Sanoj

**Comment by pazone** [comment]
Actually dpr is not depends on the site. Which browser or emulator are you using?

**Comment by sanojqa** [comment]
I am using Android Real Device Samsung Galaxy S4 and mobile browser is chrome.

**Comment by pazone** [comment]
Samsung Galaxy S4 pixel ratio is 3 by specifications. But chrome is able to reduce. Have you tried `1.5`? Anyway `3`or `1.5` should work.

A little tip: Desktop Chrome can emulate Samsung Galaxy S4. It rather more stable and easy-to-use. Have you tried [this](https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation)?

**Comment by sanojqa** [comment]
How to capture the screenshot of a specific element rather than entire page using Ashot in Mobile Web?

Say I loaded google.com in Samsung Galaxy S4. Bottom side there is a link 'About'. I need to capture it. Is it possible to do with Ashot?

**Comment by pazone** [comment]
You can use any AShot if you resolved your problem with `dpr`. You can find how to do it in ReadMe
