### ISSUE TITLE
Taking full screenshot with Ashot (IE and Safari)

### ISSUE THREAD

**Issue by seekingKnowledge** [yandex-qatools/ashot#76]
hello everyone , I am very new with Ashot, I was trying to get browser full screenshot, I can take it fine with Opera, Chrome but it repeat the first display screen image for the rest of the browser. Is there different function i need to use for different browser (safari, IE and fireforx).

please provide me a sample code and help.

your time and sample code will be much appreciated.

Cheeers

**Comment by pazone** [comment]
Hello. Could you please provide your code snippet when you are using AShot? You need different AShot configurations for Chrome and Firefox. Configuration for Firefox is more simple than for Chrome

**Comment by seekingKnowledge** [comment]
hey Pazone, thanks for the reply 
Screenshot screenshot = new Ashot(). shootingStrategy(new Viewport PastingStrategy (1000)).takeScreenshot (driver);

here is the line of the conf i use ...
please provide a sample code or any instraction for (FF, IE, Safari ) please. 

appreciate your help

**Comment by pazone** [comment]
Just remove `shootingStrategy(new Viewport PastingStrategy (1000))` - and it will work in FF, IE, and Safari. You need different AShot configurations for different browser types.

**Comment by seekingKnowledge** [comment]
thank you Pazone, but it does not work for  me , the scrolling of the page dont start and it does not capture image at all ...
please give any ashot full method if you used and it worked with windows 10.

**Comment by seekingKnowledge** [comment]
Hi Pazone 
Here is my class for Firefox, It open FF and it open the website but it does not do anything else... plus I use the same code with some tweaking the driver part for opera and that works just fine. 

`public class mytestclass {
 public WebDriver driver;

 public static void main(String[] args) {
  mytestclass main = new mytestclass();
  try {
   main.openBrowser();
  } catch (Exception e) {
   e.printStackTrace();
  }
 }

 @Test
 public void getscreenshot2() throws Exception {
  Screenshot screenshot = new AShot().takeScreenshot(driver);
  ImageIO.write(screenshot.getImage(), "PNG", new File("C:\\Temp\\screenshot.png"));

 }

 @Test
 public void openBrowser() throws Exception {
  driver = new FirefoxDriver(); 
  driver.manage().window().maximize();
  driver.get("http://www.ebay.co.uk/");
  try {
   driver.findElement(By.id("testing")).sendKeys("test");
  } catch (Exception e) {
   System.out.println("I'm in exception");
   // calls the method to take the screenshot.
   getscreenshot2();
  }
 }

 public void getscreenshot() throws Exception {
  File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
  FileUtils.copyFile(scrFile, new File("C:\\Temp\\screenshot.png"));
 }
}`

**Comment by pazone** [comment]
It looks like your test is not entering the `catch` block. Call your `getscreenshot2()` method directly after `driver.get`. And it will get screenshot.

**Comment by seekingKnowledge** [comment]
Yes it does go to catch block-because I have checked that just now. I put a message box in the getscreen.. function and I got the message box.
