### ISSUE TITLE
Configurable Indent for Blurred Image

### ISSUE THREAD

**Issue by rab2215** [yandex-qatools/ashot#79]
I have been experimenting with using the blur feature of aShot.  I have been able to get it to work, but the imageCropper is cropping too much of the page.  Is there a way to configure this to still show the entire page, but blur everything except the given webElement?

**Comment by pazone** [comment]
Try to use `new IndentCropper([desiredIndent])`. You can enlarge the space around your element by passing bigger indent value.

**Comment by rab2215** [comment]
Thanks for the quick reply, I didnt realize there was an optional parameter for the IndentCropper.  That was exactly what I was looking for.  Is there also an option somewhere to configure the degree of blur applied to the image?

**Comment by pazone** [comment]
Take a look at `BlurFilter` class. You can implement any filter you want. Also you can use `monochromeFilter`

**Comment by rab2215** [comment]
Thanks, I was able to implement my own filter.

**Comment by thasherwin** [comment]
Can you please share your code

**Comment by rab2215** [comment]
Sure, I attempted to add more blur, but in the end it lost too much context of the content surrounding the Web Element (it also wasn't too easy on the eyes).  I ended up using a filter to darken the surrounding areas 50% instead.  IMHO is better since you still get the full context of the surrounding area, but its still obvious what Web Element is intended to be focused.

```java
public class DarkFilter implements IndentFilter {

    private float scaleFactor = .5f;

    public DarkFilter() {
    }

    public DarkFilter(float scaleFactor) {
        this.scaleFactor = scaleFactor;
    }

    public BufferedImage apply(BufferedImage image) {
        RescaleOp op = new RescaleOp(scaleFactor, 0, null);
        return op.filter(image, null);
    }
}
```

**Comment by thasherwin** [comment]
Thanks:)

**Comment by pazone** [comment]
@rab2215 Could you please show the example image with your filter?

**Comment by rab2215** [comment]
With a single web element focused:

![image](https://cloud.githubusercontent.com/assets/6473132/17811445/7175c342-65e8-11e6-9563-8da944af4977.png)

with a list of input web elements focused:

![image](https://cloud.githubusercontent.com/assets/6473132/17811466/909213a2-65e8-11e6-8c39-bc783f17e6d8.png)

**Comment by rab2215** [comment]
These screenshots were taken using the chrome browser.  When using Internet explorer though, the darkened area appears completely white. 
![image](https://cloud.githubusercontent.com/assets/6473132/17816414/9b250624-65fe-11e6-900b-47b358ef07af.png)

 I have verified that the entire image is there before the filter is applied.  Any thoughts on why this would happen in IE?

**Comment by pazone** [comment]
Thank you! It looks fine! The result looks similar with `MonochromeFilter`. You are always welcome when you have any ideas about new filters.

**Comment by drundanibel** [comment]
I would like to return to the original question from rab2215: 
Is there a way to apply a filter to a WebElement without cropping the surrounding rest of the screenshot at a defined distance? I would like to keep the original screenshot in full size. Is this possible?
