### ISSUE TITLE
WebElement Screenshot does not actually take screenshot of the element

### ISSUE THREAD

**Issue by mateuszj1995** [yandex-qatools/ashot#81]
Hi,

I'm trying to feed ashot a bunch of different elements to screenshot, like this:

`ru.yandex.qatools.ashot.Screenshot myScreenshot = new AShot()
                  .takeScreenshot(_driver.getWebDriver(), element);`

But despite the element size being 94*36px, Ashot will instead take a regular screenshot of the visible bit of the page, not even scrolling to the actual position of the element. 

Am I doing something wrong?

**Comment by mateuszj1995** [comment]
Update:

When I added ".shootingStrategy(ShootingStrategies.viewportPasting(100))" it fixed the issue for buttons, but the problem persists for things that might have their own internal scroll bars, such as iframes, large overlays or other stuff. I would appreciate being pointed to a solution on that issue.

**Comment by pazone** [comment]
Sorry for missing this issue. Is it still reproducing?

**Comment by pazone** [comment]
Reopen this issue if it is still reproducing
