### ISSUE TITLE
How to set transparent color?

### ISSUE THREAD

**Issue by blink2004** [yandex-qatools/ashot#83]
Using aShot 1.5.2 version in project. And have a problem. How to set transparent color for ignorred regions of image?
Try use
`ImageDiffer imageDifferWithIgnored = new ImageDiffer().withIgnoredColor(Color.MAGENTA);`
but method withIgnoredColor() is not found in lib.

Thanks!

**Comment by pazone** [comment]
@eroshenkoam Could you please help with release?

**Comment by baev** [comment]
@blink2004 @pazone 1.5.3 was released just now

**Comment by pazone** [comment]
Nice
