### ISSUE TITLE
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only

### ISSUE THREAD

**Issue by surtur0** [yandex-qatools/ashot#86]
I am getting following warning on using the ashot lib

lis 30, 2016 12:57:14 PM org.openqa.selenium.remote.Augmenter extractRemoteWebDriver
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only
lis 30, 2016 12:57:16 PM org.openqa.selenium.remote.Augmenter extractRemoteWebDriver
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only

ashot 1.5.2
selenium 2.53.0
code:
public class ashot {

    private static WebDriver driver;

    @BeforeTest
    public void setUp() throws Exception {
        System.setProperty("webdriver.chrome.driver", "./libs/chromedriver.exe");
        DesiredCapabilities cap = DesiredCapabilities.chrome();
        driver = new ChromeDriver(cap);

    }

    @Test
    public void github() throws IOException{
        driver.get("https://github.com");
        Screenshot screenshot = new AShot()
                    .shootingStrategy(ShootingStrategies.viewportPasting(100))
                    .takeScreenshot(driver);
        ImageIO.write(screenshot.getImage(), "PNG", new File("./ashot/screen.png"));
    }

    @AfterTest
    public void close() {
        driver.quit();
    }
}

**Comment by amitrai99** [comment]
Getting the same message in my console too.

**Comment by pazone** [comment]
For sure this warning goes from [there](https://github.com/yandex-qatools/ashot/blob/1f836e49fe33f596f12f795bbde67d6296abd996/src/main/java/ru/yandex/qatools/ashot/shooting/SimpleShootingStrategy.java#L24). Some `WebDriver` implementations has no `@Augmentable` annotation and this warning tells us that webdriver has not been augmented and nothing was changed. I think it's not critical.

**Comment by ryantrevisol** [comment]
This may have been fixed by #97
