### ISSUE TITLE
Is there a way to set some ImageDiff comparison coefficient ?

### ISSUE THREAD

**Issue by tlytvyn** [yandex-qatools/ashot#94]
I have screenshots that have minor differences and I would like to ignore them. I don't want to ignore webElements while capturing screenshots, - I just want to set some comparison rate during compare procedure, let say like uncertainty 5% between screenshots. Is it possible ?

**Comment by dimand58** [comment]
`  @Test
    public void testSetDiffSizeTrigger() throws Exception {
        ImageDiff diff = imageDiffer.makeDiff(IMAGE_A_SMALL, IMAGE_B_SMALL);
        assertThat(diff.withDiffSizeTrigger(624).hasDiff(), is(false));
        assertThat(diff.withDiffSizeTrigger(623).hasDiff(), is(true));
    }`

I think this what you want =)

**Comment by tlytvyn** [comment]
@dimand58 Yeap, this is it, thanx a lot

**Comment by Anand093** [comment]
When i do the same i got error **Expected: is got:**

Could u plz help me on this?

**Comment by tlytvyn** [comment]
@Anand093 diff.withDiffSizeTrigger() works for me

**Comment by Anand093** [comment]
@tlytvyn Shall i add statement like this
  assertThat(diff.withDiffSizeTrigger(10),is(false));

**Comment by Anand093** [comment]
Hi @tlytvyn,
Thanks for your kind help!
When i use diff.withDiffSizeTrigger(1), it shows compare result true in all the cases although actual & expected screen in entirely different.
