### ISSUE TITLE
Unable to capture proper full screenshot in Chrome

### ISSUE THREAD

**Issue by techGen** [yandex-qatools/ashot#96]
I am using below code to capture screenshot in chrome but it capture same thing multiple times in screenshot. I just want to take full screenshot of page in chrome browser.

Screenshot screenshot = new AShot()
				  .shootingStrategy(ShootingStrategies.viewportPasting(500))
				  .takeScreenshot(driver);

**Comment by ryantrevisol** [comment]
It will be difficult to reproduce the issue without some additional information. For example, the exact code you posted (with a shorter scroll timeout) is working perfectly for me: 

- Google Chrome 57/58 
- Chromedriver 2.28
- Mac OS Sierra/ OS X El Capitan
- Selenium 3.3.0
- Java 8

**Comment by nikhilkr123** [comment]
I am expecting to see a full screenshot of the web page even though browser window size is reduced.
```
WebDriver driver = new ChromeDriver();
driver.get("https://www.google.com.au");
Screenshot screenshot = 
     new AShot().shootingStrategy(ShootingStrategies.viewportPasting(500)).takeScreenshot(driver);
ImageIO.write(screenshot.getImage(), "PNG", new File("screen.png");
driver.manage().window().setSize(new Dimension(500, 600));
```

- ChromeDriver 2.28.455517
- Selenium 3.3.1
- Java 1.8
- Chrome 58
- Mac OS Sierra

**Comment by pazone** [comment]
Guys, you can find the answer here: https://github.com/yandex-qatools/ashot/issues/104
