### ISSUE TITLE
Capturing screenshot of scrolling div element 

### ISSUE THREAD

**Issue by angmenghua** [yandex-qatools/ashot#99]
Hi, 

I don't seem to figure a way to be able to take a screenshot of a div element that is scrollable.
Is this supported?

Thanks!
Jason

**Comment by pazone** [comment]
Hi, @angmenghua. Do you mean that content of your element is partially visible? How do you suppose to take a screenshot of whole content? To my mind in case if you are using it for testing the workaround is to take one screenshot with content on top of the div and second screenshot when content is in the bottom.
